### ISSUE TITLE
Adding workshop host map possible 

### ISSUE THREAD

**Issue by DOMINOzHNS** [justinnobledev/cs2-mapchooser#12]
Hello, the problem is non of the rtv-plugins work for me even using "ds_workshop_changelevel" for workshop maps - even when i add ws: at the start of the map.
The thing working for me is using "host_workshop_map XXXXXXXXXX"
Can  you add this option to this rtv plugin? Or im wrong with it?
Will it work for rtv plugin or it is obvius that it will not work?
If it has a chance You can also try to add something like this: 
https://github.com/Cruze03/cs2_WorkshopDefaultMap/
but also using "host_workshop_map XXXXXXXXXX"
Thanks, Bye

**Comment by justinnobledev** [comment]
When you say adding ws: at the start doesnt work do you mean if you try ws:fileid or ws:map_name if you mean file id then yes that was never meant to be supported, but could potentially be added.

I also don't plan on adding a default map to this plugin, it is a map vote plugin not an all in one plugin, No reason to integrate the other plugin in this when it already works fine

**Comment by DOMINOzHNS** [comment]
And can you add this feature?

**Comment by justinnobledev** [comment]
I'm going to say no, just use a collection there would be no benefit to using `host_workshop_map` over a collection. It would add a bunch of unneeded complexity and would require a whole new map.txt
