### ISSUE TITLE
rtv commands

### ISSUE THREAD

**Issue by rcon420** [justinnobledev/cs2-mapchooser#14]
Could you add triggers like this maybe in the plugin? most people are probbaly used to use rtv command without ! or /

```
            if (@event.Text.Trim() == "rtv"
            || @event.Text.Trim() == "!rtv"
            || @event.Text.Trim() == "/rtv")
```
and you you please add check for HLTV and BOTS? 

  ```
get => Utilities.GetPlayers()
                .Where(x => !x.IsBot && !x.IsHLTV)
                .Count();
```

**Comment by justinnobledev** [comment]
Yeah I can add that at some point

**Comment by justinnobledev** [comment]
This is being added in the next version should be out in a few days just have to do some testing.
