### ISSUE TITLE
Use build-in timer instead of mp_timelimit

### ISSUE THREAD

**Issue by LaplaceTor** [justinnobledev/cs2-mapchooser#15]
i cannot change map when mp_timelimit end
i use this plugin in bhop/surf/kz server and set mp_timelimit as 20, roundtime as 0
when timelimit end , would show the next map vote but after vote ,game would goto the end but just reload the recent map, not change map
and another thing is , if they want to extend, they still need to wait for the map reloading
If use build-in timer, i can just set mp_timelimit 0, and would not reload the map after vote extend

**Comment by justinnobledev** [comment]
My guess for this is you have `mp_ignore_round_win_conditions 1` set but dont have `EnforceTimeLimit` set in the config. I am running this on my surf server and have no issues (sorry for the long reply time)
