### ISSUE TITLE
Round Draw bug

### ISSUE THREAD

**Issue by kingdragox99** [justinnobledev/cs2-mapchooser#19]
**Describe the bug**
Sometimes in my retake server, for no apparent reason, round just draw and restart.

**To Reproduce**
1. Sometimes when a player joins.
2. But most of the time it's for no reason.

**Expected behavior**
Fix it.

**Server Info**
 - OS: Linux
 - CSS Version 1.65 / 1.66 / 1.67
 - Plugin Version last

**Comment by justinnobledev** [comment]
The plugin currently runs on an independent timer, so what is happening is that timer runs out and tries to trigger the end of map screen. I have plans to remove that system and just listen for the end of map event and do the map switch there
