### ISSUE TITLE
How to set up a voting pool using the Creative Workshop map?

### ISSUE THREAD

**Issue by 1370533448** [justinnobledev/cs2-mapchooser#21]
When I add the workshop map named ws:awp_india_hd, it appears in the voting pool. However, it seems that at the end of the game, when players vote for the original CS2 game maps, the map will be changed back to the default mode. Currently, I can use +host_workshop_map 3146105097 as the server's launch map parameter. Should I write ws:3146105097 in the map pool, or should I download the map from the Steam Workshop and upload it to the csgo/map folder before inputting ws:awp_india_hd into the map pool?

**Comment by justinnobledev** [comment]
This plugin works with workshop collections not host_workshop_map, so you need to setup a collection to use workshop maps. If you mean default mode like +game_mode this plugin doesnt edit that at all.
