### ISSUE TITLE
the mapchooser plugin doesnt work propley

### ISSUE THREAD

**Issue by zurls2021** [justinnobledev/cs2-mapchooser#22]
it keeps starting early and then at the end of the map time it repeats the same map  can u get that fixed pls

**Comment by zurls2021** [comment]
it pops up at the beggining of the round when the game starts

**Comment by justinnobledev** [comment]
I'm not entirely sure what the issue you are encountering is. I am going to post an update in the next couple of days try that if you are still using this plugin.
