### ISSUE TITLE
No vote is displayed

### ISSUE THREAD

**Issue by ToHold** [justinnobledev/cs2-mapchooser#27]
**Describe the bug**
css_rtv or !rtv just change map to the next map without asking a vote. What should I do to display the vote list ?

**Screenshots**
Here is my config :
![image](https://github.com/justinnobledev/cs2-mapchooser/assets/38291374/c82b3db5-a090-4eef-9fc4-fb8f38dba6ae)

Here is maps.txt : 
![image](https://github.com/justinnobledev/cs2-mapchooser/assets/38291374/c25860f9-e4c2-4758-8084-d4472844a0ea)

By the way there was no maps.txt when I installed the plugin, I had to create it.

**Server Info**
 - OS: debian 12

**Comment by justinnobledev** [comment]
What is your mp_timelimit

**Comment by ToHold** [comment]
didn't change anything

**Comment by justinnobledev** [comment]
> didn't change anything

in your config what do you have `mp_timelimit` set to if it is something <= VoteStartTime it will instantly make a vote and that is what seems to be happening

**Comment by ToHold** [comment]
I tried with mp_timelimit 100 and mp_timelimit 1000 but it does the same

**Comment by justinnobledev** [comment]
🤷 I'm using the same latest version on my server and when I rtv if no vote has happened it starts a map vote

**Comment by ToHold** [comment]
!rtv still change to the next map

**Comment by ToHold** [comment]
I'll record my screen might help

**Comment by ToHold** [comment]
Here's the video : https://youtu.be/-6atwC1q82Y

**Comment by ToHold** [comment]
Ok i found it, my bad, I have the wrong .cfg execed so mp_timelimit 0 you were right thank you !
