### ISSUE TITLE
maplist from workshop collection

### ISSUE THREAD

**Issue by Arterias1** [justinnobledev/cs2-mapchooser#28]
Idea to improve:

When we have a workshop collection, bypass the mapcycle.txt / maplist, plugin will pickup maps only from the collection that is designed on the cs2server.cfg collection.
This way we can maintain server with custom maps (surf/kz) from one single point : the workshop collection

**Comment by justinnobledev** [comment]
The main issue I see with doing this is if you a map name differs from the workshop title it'd take a lot more work to determine the map name, if there was some way to hook console output from commands I can come back to visit this topic, but for now I think this is just a bit out of scope. Feel free to make a PR if your interested in doing this though
