### ISSUE TITLE
End of mp_timelimit map change broken [BUG]

### ISSUE THREAD

**Issue by Magic8Ballin** [justinnobledev/cs2-mapchooser#3]
When running the plugin the voting system works correctly and a nextmap is chosen.

When the server mp_timelimit runs out, the map is not changing to the chosen map. Instead the default cs2 map voting takes place and the server votes for a map in the endgame ui.

Are there any commands that must be changed to have the mapchooser plugin override the cs2 voting system?

**Comment by justinnobledev** [comment]
Fixed, sorry about that!
